### ISSUE TITLE
errata

### ISSUE THREAD

**Issue by Lessebo** [smarthome-mit-openhab2/2018_ErsteAuflage#3]
Sehr geehrte Frau Spiller,

mir sind ein paar Fehler aufgefallen

Seite 55
falsch: systemctl restart openhab2.service
richtig: sudo systemctl restart openhab2.service
Als Linux-Neuling bin ich in die "root"-Falle auf Seite 55 Ihres Buches gestolpert.
"systemctl restart openhab2.service" ohne vorangestelltes "sudo" fragt nach dem Passwort des users "root". Also habe ich mich auf die Suche nach dem von anderen Systemen her bekannten users/administrators "root" und dessen Passwort begeben - ohne Erfolg, was Sie nicht wundern wird.

Seite 59
falsch: ssh -p 8101 -1 openhab localhost
richtig: ssh -p 8101 openhab@localhost
Möglicherweise einer Versionsänderung geschuldet?

Seite 83
falsch: https://marketplace.visualstudio.com/items?item-Name=openhab.openhab
richtig: https://marketplace.visualstudio.com/items?itemName=openhab.openhab

Mit freundlichen Grüßen
Michael Pelz

**Comment by dirkmacke** [comment]
Seite 59: Vmtl. handelt es sich hier um einen Tippfehler und gemeint war

`ssh -p 8101 **-l** openhab localhost`

Die vorgeschlagene Lösung 

`ssh -p 8101 openhab@localhost`

funktioniert natürlich auch.

**Comment by sysadmama** [comment]
Documented with abc7e5d6b6b2ebff6ea54f84347989ac2be2ad27; will be handled within second edition.
