### ISSUE TITLE
Kap. 25: Das System auf einer externen Platte betreiben

### ISSUE THREAD

**Issue by TomDidi** [smarthome-mit-openhab2/2018_ErsteAuflage#4]
Hallo Frau Spiller,

zunächst einmal noch Gratulation zu diesem tollen Kompendium, welches auch Anfängern wie mir eine neue Welt zeigt. Danke dafür.

Ich arbeite gerade Kap. 25 durch, um das OpenHAB-2-Setup auf einer SSD laufen zu lassen.
Dabei sind drei Fragen aufgetaucht.

1.  **alle Befehle in Kap. 25** lassen sich nur mit "sudo" durchführen, im Buch in Kap. 25 stehen die Befehle ohne "sudo". Ohne "sudo" können die Befehle in meiner OpenHabian Installation auf einem Pi3 nicht ausgeführt werden.

**2. Kap. 25.4 Kopieren der Datei:** die Eingabe von
sudo rsync -avzxS /  /mnt/raspissd schließt bei mir mit folgender Fehlermeldung ab:
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1196) [sender=3.1.2]. Kennen Sie diese Warnung?

3. **In Kap. 25.6 Neustart: im 3. Absatz schreiben Sie:** 
"Alle schreibenden Zugriffe erfolgen von nun an auf der externen Platte - mit Ausnahme von system-Updates, die neue Kernel einbringen." Sind damit auch apt Updates, Snapshot Updates, Milestone Updates und wie gestern das neue 2.4 Release von OH gemeint? Wenn ja, wie kann dann die SSD "aktualisiert" werden.

Sollten meine Fragen zu naiv sein, tut es mir leid, aber ich lerne hart eine neue Welt kennen.

Mit freundlichen Grüßen
Thomas Dietrich (habe nur eine Namensgleicheit mit dem "Großen Namensvetter")

**Comment by sysadmama** [comment]
Hallo und ein frohes neues Jahr Ihnen!

Ich versuche mal, möglichst prägnant zu antworten.

* **Zu 1:** Sie haben völlig recht. `fdisk`, `mkfs`& Co. erfordern üblicherweise `root`-Rechte – das sind Dinge, die für mich so klar sind, dass ich ganz gerne mal vergesse sie zu erwähnen – und das kostet Sie wiederum Zeit. Eine mögliche Lösung des Problems haben Sie selbst bereits erarbeitet: setzen Sie allen Aufrufen in Kapitel 25 ein `sudo` voran. Ich erfasse das gleich in der Korrekturen-Datei und vermerke es für den Nachdruck entsprechend.

* **Zu 2:** Wenn Sie `rsync` starten, tun Sie das ja in einem laufenden System; es hat File-Handles offen, vielleicht gerade temporäre Dateien irgendwo in Arbeit usw. Beim Start von `rsync` ermittelt dieser, welche Dateien er von A nach B übertragen wird und beginnt mit der Übertragung erst, wenn diese *Übersicht* fertig ist. Wenn nun beispielsweise eine temporäre Datei geschlossen wird, bevor es zur Übertragung kam, dann merkt `rsync` das und quittiert es mit der von Ihnen zitierten Meldung. Es kommt dann darauf an, um welche Dateien es sich handelt – aber üblicherweise ist die Meldung in unserem Kontext unkritisch, und diesen Hinweis werde ich dem Abschnitt auch noch anfügen.

* **Zu 3:** Im Buch finden Sie ja auf S. 456 den Hinweis, dass es inzwischen grundsätzlich möglich ist, das **ganze** System auf die externe Platte auszulagern, dieser Ansatz aufgrund technischer Schwierigkeiten im Buch aber nicht aufgegriffen wurde. Stattdessen wird auf die externe Platte alles **außer `/boot`** gelegt – und in `/boot` findet sich der Kernel des Betriebssystems, also das, was bei einem Upgrade des Betriebssystems üblicherweise erneuert wird. Sie (bzw. Ihr Linux) mountet also `/` von der externen Platte, `/boot` hingegen weiterhin von der SD-Karte. Für einen Aufruf von `apt` ist das aber irrelevant, so lange alle Partitionen beschreibbar gemountet sind.

Jetzt wurde es doch ziemlich viel Text... Bin ich verständlich? :sunglasses:

Cheers,
  Marianne

**Comment by sysadmama** [comment]
Documented with 496e684d6309fbd42ba5fe7023e78fb0ac114572; will be handled within first reprint.
