### ISSUE TITLE
Yahoo Wetterdienst

### ISSUE THREAD

**Issue by MeisterP80** [smarthome-mit-openhab2/2018_ErsteAuflage#6]
Hallo,
das Beispiel mit dem Yahoo Wetter Binding ist leider nicht mehr durchführbar.
https://community.openhab.org/t/yahoo-weather-binding-free-weather-api-services-canceled/56172
Wird es dazu eine Alternative geben?

**Comment by sysadmama** [comment]
Hallo,

ich verstehe die Frage nicht: schon am 27. Dezember 2018 habe ich diese Problematik in [README.md](https://github.com/smarthome-mit-openhab2/2018_ErsteAuflage/blob/master/README.md) aufgegriffen. Ob YAHOO! hierzu eine Alternative bieten wird weiß ich nicht; die erwähnten DarkSky und OpenWeatherMap bieten ihre Dienste offenbar unverändert an.

Viele Grüße,
  Marianne Spiller

**Comment by MeisterP80** [comment]
Auch wenn die Frage vielleicht zu unverständlich war passt dennoch der Verweis auf die README.md.
Hab die Infos zu dem Thema einfach übersehen. 
Besten Dank
