### ISSUE TITLE
Kapitel 3: Kennwortänderung der OpenHAB-Konsole

### ISSUE THREAD

**Issue by msimat** [smarthome-mit-openhab2/2018_ErsteAuflage#7]
In Kapitel 3.2.1, Seite 59 wird zur Passwortänderung des OpenHAB-Konsolenbenutzers auf 2.3.5 verwiesen. Dort wird aber das Kennwort eines Systembenutzers geändert. Die Konsolen-Kenwortänderung ist beispielsweise unter https://www.openhab.org/docs/administration/console.html#changing-the-password beschrieben.

**Comment by msimat** [comment]
Ok, man hätte nur bis 3.2.2 weiterlesen müssen... Trotzdem ist die Referenz auf Kapitel 2.3.5 irritierend.

**Comment by sysadmama** [comment]
Hallo,

ich notiere es mal für die Zukunft - ist aber natürlich nichts, woran man jetzt konkret etwas ändern könnte.

Danke für den Hinweis,
  Marianne
