### ISSUE TITLE
Tippfehler auf Seite 55 von 2018 Ausgabe  

### ISSUE THREAD

**Issue by nielssch** [smarthome-mit-openhab2/2018_ErsteAuflage#8]
Hallo, 
Danke für das tolle Buch. Auf Seite 55 ist ein falscher Pfad angeben. Er lautet 
/etc/default/openhab2 und nicht
/etc/defaults/openhab2
Zumindest in meiner Installation.
Viele Grüße
NIels

**Comment by sysadmama** [comment]
Hallo,

kennen Sie schon [die Korrekturen zum Buch](https://github.com/smarthome-mit-openhab2/2018_ErsteAuflage/blob/master/doc/Korrekturen.md)? Ich hab extra nochmal nachgeschlagen – die Sache mit dem überflüssigen `s` hatte ich da [bereits eingetragen](https://github.com/smarthome-mit-openhab2/2018_ErsteAuflage/commit/e2da213c268bd70866b54bd2753051e423777b01#diff-4de4075c18d9ffc33b267ff44fe08fe5) :)

Trotzdem vielen Dank für die Rückmeldung! Und falls Sie die Korrektur-Seite noch nicht kennen schauen Sie ruhig mal hinein, der eine oder andere Fehler hat es trotz x-fachem Redigierens leider in die Printausgabe geschafft...

Viele Grüße,
  Marianne Spiller
